### ISSUE TITLE
No more images

### ISSUE THREAD

**Issue by rapha8l** [derat/twittuh#1]
Hi,

Thanks for your program, it's great
Though since today, images stopped to load in feeds
Thanks

**Comment by derat** [comment]
I'm glad you're finding it useful!

*   Could you give me an example timeline that you're seeing this problem for?
*   Can you run with the `-verbose` flag and attach the output?
*   Which format are you using (atom, json, rss)?

I'm seeing embedded images in feeds that were created about two hours ago, and it also looks like images are included when I run `twittuh -force -format json -pages 1 -verbose librarycongress librarycongress.json` right now.

**Comment by rapha8l** [comment]
twittuh -force -format json -pages 1 -verbose archillect archillect.json
I've been forced to add .txt to be able to upload it
[archillect.json.txt](https://github.com/derat/twittuh/files/5268966/archillect.json.txt)

My command is : /usr/local/bin/twittuh archillect /tmp/go-touit.rss and images are broken

Thanks a lot for your help

**Comment by derat** [comment]
Thanks for the details!

Hmm, in your attached file (and in what I get when I scrape the same feed), it looks like the `content_html` properties include `<img>` tags. For example, the top item has this content:

```
"\u003cdiv class=\"tweet-text\" data-id=\"1308780876206092288\"\u003e\n      \u003cdiv class=\"dir-ltr\" dir=\"ltr\"\u003e  \u003ca href=\"https://t.co/8G3ZFneKGP\" data-pre-embedded=\"true\" rel=\"nofollow\" data-entity-id=\"1308780873085485059\" dir=\"ltr\" data-url=\"https://twitter.com/archillect/status/1308780876206092288/photo/1\" data-tco-id=\"8G3ZFneKGP\" class=\"twitter_external_link dir-ltr tco-link has-expanded-path\" target=\"_top\" data-expanded-path=\"/archillect/status/1308780876206092288/photo/1\"\u003e\u003cimg src=\"https://pbs.twimg.com/media/Eim5RRUWAAM6BbV.jpg:small\"/\u003e\u003c/a\u003e\n\u003c/div\u003e\n    \u003c/div\u003e"
```

Decoded and pretty-printed, I think that that turns into:

```html
<div class="tweet-text" data-id="1308780876206092288">
  <div class="dir-ltr" dir="ltr">
    <a
      href="https://t.co/8G3ZFneKGP"
      data-pre-embedded="true"
      rel="nofollow"
      data-entity-id="1308780873085485059"
      dir="ltr"
      data-url="https://twitter.com/archillect/status/1308780876206092288/photo/1"
      data-tco-id="8G3ZFneKGP"
      class="twitter_external_link dir-ltr tco-link has-expanded-path"
      target="_top"
      data-expanded-path="/archillect/status/1308780876206092288/photo/1"
      ><img src="https://pbs.twimg.com/media/Eim5RRUWAAM6BbV.jpg:small"
    /></a>
  </div>
</div>
```

There's an `<img>` tag pointing at https://pbs.twimg.com/media/Eim5RRUWAAM6BbV.jpg:small at the end there, and it looks properly-formatted to me and I'm able to load it in my browser -- let me know if you see something that I'm missing.

What software are you using to read the feed?

**Comment by rapha8l** [comment]
Strange, I'm using tt-rss self hosted
Could be a tt-rss issue, as I'm on git

**Comment by rapha8l** [comment]
Indeed it works in a desktop rss reader (liferea)
Sorry for the noise and thanks again !
