### ISSUE TITLE
A way to output directly to stdout instead of writing to file?

### ISSUE THREAD

**Issue by guihkx** [derat/twittuh#10]
I tried using `twittuh -force blah /dev/stdout` but I get this:

```
2021/02/03 20:25:45 Failed creating feed file: open /dev/.stdout.025320600: permission denied
```

Thanks

**Comment by derat** [comment]
Sure, I think that this would be easy to support. Would being able to pass `-` in place of a filename work for you?

**Comment by guihkx** [comment]
Ah yes, I tried with `-` as well, so yeah, that'd be perfect. Thanks
